In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf
import keras

### เหมือน preprocess แบบ 00 แต่ไม่ได้ต้องการให้เป็น tensor df ต้องการให้เป็น numpy

In [2]:
num_range = 25
window_size = 5
output_size = 1


series = np.arange(num_range)

#### tensor dataset

In [3]:
ds = tf.data.Dataset.from_tensor_slices(series)
ds

<TensorSliceDataset shapes: (), types: tf.int32>

In [4]:
ds.as_numpy_iterator()

In [5]:
ds.numpy()

AttributeError: 'TensorSliceDataset' object has no attribute 'numpy'

In [6]:
for i in ds.as_numpy_iterator():
    print(i, end='\t')

0	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	

#### windowing

In [7]:
ds = tf.data.Dataset.from_tensor_slices(series)
ds = ds.window(window_size+output_size, shift=1, drop_remainder=True)
ds = ds.flat_map(lambda window: window.batch(window_size+output_size))
ds = ds.map(lambda window: (window[:-output_size], window[-output_size:]))

In [8]:
ds

<MapDataset shapes: ((None,), (None,)), types: (tf.int32, tf.int32)>

In [9]:
ds.as_numpy_iterator()

In [10]:
ds.numpy()

AttributeError: 'MapDataset' object has no attribute 'numpy'

In [15]:
for data in ds.as_numpy_iterator():
    x, y = data
    print(f"{x} \t {y}")

[0 1 2 3 4] 	 [5]
[1 2 3 4 5] 	 [6]
[2 3 4 5 6] 	 [7]
[3 4 5 6 7] 	 [8]
[4 5 6 7 8] 	 [9]
[5 6 7 8 9] 	 [10]
[ 6  7  8  9 10] 	 [11]
[ 7  8  9 10 11] 	 [12]
[ 8  9 10 11 12] 	 [13]
[ 9 10 11 12 13] 	 [14]
[10 11 12 13 14] 	 [15]
[11 12 13 14 15] 	 [16]
[12 13 14 15 16] 	 [17]
[13 14 15 16 17] 	 [18]
[14 15 16 17 18] 	 [19]
[15 16 17 18 19] 	 [20]
[16 17 18 19 20] 	 [21]
[17 18 19 20 21] 	 [22]
[18 19 20 21 22] 	 [23]
[19 20 21 22 23] 	 [24]


#### อาจจะเพิ่มการ shuffle

```python
ds = tf.data.Dataset.from_tensor_slices(series)
ds = ds.window(window_size+output_size, shift=1, drop_remainder=True)
ds = ds.flat_map(lambda window: window.batch(window_size+output_size))
ds = ds.shuffle(shuffle_buffer)
ds = ds.map(lambda window: (window[:-output_size], window[-output_size:]))
```

### แปลงให้เป็น numpy

In [18]:
ds = tf.data.Dataset.from_tensor_slices(series)
windows = ds.window(window_size + output_size, shift=1, drop_remainder=True)
ds = windows.flat_map(lambda window: window.batch(window_size + output_size))
# ds = ds.shuffle(shuffle_buffer)
ds = ds.map(lambda window: (window[:-output_size], window[-output_size:]))

In [21]:
ds.as_numpy_iterator()

In [22]:
list(ds.as_numpy_iterator())

[(array([0, 1, 2, 3, 4]), array([5])),
 (array([1, 2, 3, 4, 5]), array([6])),
 (array([2, 3, 4, 5, 6]), array([7])),
 (array([3, 4, 5, 6, 7]), array([8])),
 (array([4, 5, 6, 7, 8]), array([9])),
 (array([5, 6, 7, 8, 9]), array([10])),
 (array([ 6,  7,  8,  9, 10]), array([11])),
 (array([ 7,  8,  9, 10, 11]), array([12])),
 (array([ 8,  9, 10, 11, 12]), array([13])),
 (array([ 9, 10, 11, 12, 13]), array([14])),
 (array([10, 11, 12, 13, 14]), array([15])),
 (array([11, 12, 13, 14, 15]), array([16])),
 (array([12, 13, 14, 15, 16]), array([17])),
 (array([13, 14, 15, 16, 17]), array([18])),
 (array([14, 15, 16, 17, 18]), array([19])),
 (array([15, 16, 17, 18, 19]), array([20])),
 (array([16, 17, 18, 19, 20]), array([21])),
 (array([17, 18, 19, 20, 21]), array([22])),
 (array([18, 19, 20, 21, 22]), array([23])),
 (array([19, 20, 21, 22, 23]), array([24]))]

In [23]:
np.array(list(ds.as_numpy_iterator()))

array([[array([0, 1, 2, 3, 4]), array([5])],
       [array([1, 2, 3, 4, 5]), array([6])],
       [array([2, 3, 4, 5, 6]), array([7])],
       [array([3, 4, 5, 6, 7]), array([8])],
       [array([4, 5, 6, 7, 8]), array([9])],
       [array([5, 6, 7, 8, 9]), array([10])],
       [array([ 6,  7,  8,  9, 10]), array([11])],
       [array([ 7,  8,  9, 10, 11]), array([12])],
       [array([ 8,  9, 10, 11, 12]), array([13])],
       [array([ 9, 10, 11, 12, 13]), array([14])],
       [array([10, 11, 12, 13, 14]), array([15])],
       [array([11, 12, 13, 14, 15]), array([16])],
       [array([12, 13, 14, 15, 16]), array([17])],
       [array([13, 14, 15, 16, 17]), array([18])],
       [array([14, 15, 16, 17, 18]), array([19])],
       [array([15, 16, 17, 18, 19]), array([20])],
       [array([16, 17, 18, 19, 20]), array([21])],
       [array([17, 18, 19, 20, 21]), array([22])],
       [array([18, 19, 20, 21, 22]), array([23])],
       [array([19, 20, 21, 22, 23]), array([24])]], dtype=object)

In [25]:
ds = tf.data.Dataset.from_tensor_slices(series)
windows = ds.window(window_size + output_size, shift=1, drop_remainder=True)
ds = windows.flat_map(lambda window: window.batch(window_size + output_size))
# ds = ds.shuffle(shuffle_buffer)
ds = ds.map(lambda window: (window[:-output_size], window[-output_size:]))

ds = np.array(list(ds.as_numpy_iterator()))

In [28]:
ds[:, 0]

array([array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5]),
       array([2, 3, 4, 5, 6]), array([3, 4, 5, 6, 7]),
       array([4, 5, 6, 7, 8]), array([5, 6, 7, 8, 9]),
       array([ 6,  7,  8,  9, 10]), array([ 7,  8,  9, 10, 11]),
       array([ 8,  9, 10, 11, 12]), array([ 9, 10, 11, 12, 13]),
       array([10, 11, 12, 13, 14]), array([11, 12, 13, 14, 15]),
       array([12, 13, 14, 15, 16]), array([13, 14, 15, 16, 17]),
       array([14, 15, 16, 17, 18]), array([15, 16, 17, 18, 19]),
       array([16, 17, 18, 19, 20]), array([17, 18, 19, 20, 21]),
       array([18, 19, 20, 21, 22]), array([19, 20, 21, 22, 23])],
      dtype=object)

In [29]:
ds[:, 1]

array([array([5]), array([6]), array([7]), array([8]), array([9]),
       array([10]), array([11]), array([12]), array([13]), array([14]),
       array([15]), array([16]), array([17]), array([18]), array([19]),
       array([20]), array([21]), array([22]), array([23]), array([24])],
      dtype=object)

#### เอา dtype = object ออก

In [31]:
np.array(ds[:, 0].tolist())

array([[ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13],
       [10, 11, 12, 13, 14],
       [11, 12, 13, 14, 15],
       [12, 13, 14, 15, 16],
       [13, 14, 15, 16, 17],
       [14, 15, 16, 17, 18],
       [15, 16, 17, 18, 19],
       [16, 17, 18, 19, 20],
       [17, 18, 19, 20, 21],
       [18, 19, 20, 21, 22],
       [19, 20, 21, 22, 23]])

# สรุป

In [33]:
def windowing_arr_X_Y(series, window_size, output_size=1, shuffle_buffer=1000):
    """windowing the input series to ML train-dataset
        window_size: time step of input
        output_size: time step of output/forcast/predicted
        return: x, y numpy array
    """

    ds = tf.data.Dataset.from_tensor_slices(series)
    windows = ds.window(window_size + output_size, shift=1, drop_remainder=True)
    ds = windows.flat_map(lambda window: window.batch(window_size + output_size))
    ds = ds.shuffle(shuffle_buffer)
    ds = ds.map(lambda window: (window[:-output_size], window[-output_size:]))
    ds = np.array(list(ds.as_numpy_iterator()))
    x = np.array(ds[:, 0].tolist())
    y = np.array(ds[:, 1].tolist())
    return x, y