In [1]:
import tensorflow as tf
import numpy as np

## Data

X กับ Y เกี่ยวข้องกันยังไง?


In [2]:
X = [-1, 0, 1, 2, 3, 4]
Y = [-3, -1, 1, 3, 5, 7]

> y = 2x - 1

In [3]:
# Y = 2*X - 1
2*np.array(X) - 1

array([-3, -1,  1,  3,  5,  7])

## first neural network

In [4]:
model = tf.keras.models.Sequential([tf.keras.layers.Dense(units=1, input_shape=[1])])

In [5]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [6]:
Xs = np.array(X, dtype=np.float64)
Ys = np.array(Y, dtype=np.float64)

In [7]:
model.fit(Xs, Ys, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 4ms/step - loss: 12.5508
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 10.1007
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 8.1684
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 6.6437
Epoch 5/500
1/1 [==============================] - 0s 2ms/step - loss: 5.4396
Epoch 6/500
1/1 [==============================] - 0s 2ms/step - loss: 4.4879
Epoch 7/500
1/1 [==============================] - 0s 2ms/step - loss: 3.7349
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 3.1382
Epoch 9/500
1/1 [==============================] - 0s 2ms/step - loss: 2.6647
Epoch 10/500
1/1 [==============================] - 0s 2ms/step - loss: 2.2882
Epoch 11/500
1/1 [==============================] - 0s 2ms/step - loss: 1.9880
Epoch 12/500
1/1 [==============================] - 0s 2ms/step - loss: 1.7480
Epoch 13/500
1/1 [==============================] - 0s 2ms/

In [8]:
model.predict(Xs)

array([[-2.9894063],
       [-0.9919899],
       [ 1.0054264],
       [ 3.002843 ],
       [ 5.000259 ],
       [ 6.9976754]], dtype=float32)

In [9]:
model.predict([10.0])

array([[18.982174]], dtype=float32)